name: C/C++ CI

on:
  push:
    branches: [ make_build ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    continue-on-error: true
    
    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make clean
      run: make clean
